apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: apps
spec:
  interval: 10m
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    semver: ">6.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  serviceAccountName: dev-team
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: podinfo
  values:
    hpa:
      enabled: true
      maxReplicas: 2
      cpu: 90
