name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Flux
        uses: fluxcd/flux2/action@af67405ee43a6cd66e0b73f4b3802e8583f9d961 #v2.5.0
      - run: make up
      - run: make sync
      - run: make down
