name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@871be9b40d53627786d3a3835a3ddba1e3234bd2 #v2.8.3
      - name: Setup Flux Operator CLI
        uses: controlplaneio-fluxcd/flux-operator/actions/setup@c5505a455515f0ea78e04ff6f380cba8fe42a357 #v0.45.1
      - run: make up
      - run: make sync
      - run: make ls
      - run: make down
